git:
  quiet: true

os: linux

language: node_js

node_js:
  - "14"
  - "12"
  - "10"

env:
  global:
    - DEBUG=topical-pubsub

install:
  - npm install

script:
  - npm test

after_success:
  - npm run cover:report
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
